/**
 * Below are the list of SCORM error codes specified according to its "Run-Time" standard.
 * For more information, please refer to https://scorm.com/scorm-explained/technical-scorm/run-time/run-time-reference/
 */
export enum ErrorCodes {
  NO_ERROR = 0,
  GENERAL_EXCEPTION = 101,
  GENERAL_INITIALIZATION_FAILURE = 102,
  ALREADY_INITIALIZED = 103,
  CONTENT_INSTANCE_TERMINATED = 104,
  GENERAL_TERMINATION_FAILURE = 111,
  TERMINATION_BEFORE_INITIALIZATION = 112,
  TERMINATION_AFTER_TERMINATION = 113,
  RETRIEVE_DATA_BEFORE_INITIALIZATION = 122,
  RETRIEVE_DATA_AFTER_TERMINATION = 123,
  STORE_DATA_BEFORE_INITIALIZATION = 132,
  STORE_DATA_AFTER_TERMINATION = 133,
  COMMIT_BEFORE_INITIALIZATION = 142,
  COMMIT_AFTER_TERMINATION = 143,
  GENERAL_ARGUMENT_ERROR = 201,
  GENERAL_GET_FAILURE = 301,
  GENERAL_SET_FAILURE = 351,
  GENERAL_COMMIT_FAILURE = 391,
  UNDEFINED_DATA_MODEL_ELEMENT = 401,
  UNIMPLEMENTED_DATA_MODEL_ELEMENT = 402,
  DATA_MODEL_ELEMENT_VALUE_NOT_INITIALIZED = 403,
  DATA_MODEL_ELEMENT_IS_READ_ONLY = 404,
  DATA_MODEL_ELEMENT_IS_WRITE_ONLY = 405,
  DATA_MODEL_ELEMENT_TYPE_MISMATCH = 406,
  DATA_MODEL_ELEMENT_VALUE_OUT_OF_RANGE = 407,
  DATA_MODEL_DEPENDENCY_NOT_ESTABLISHED = 408
}
